MIN_BUCKET_SIZE_SPLIT = 30
MIN_BUCKET_SIZE_MISSING = 40

MIN_COHESION_SPLIT = 0.75
MIN_COHESION_MISSING = 0.80
MIN_COHESION_KEEP = 0.75
MAX_COHESION_NO_ACTION = 0.60

MIN_CLUSTER_RATIO = 0.20
DOMINANT_CLUSTER_RATIO = 0.70

MAX_INTER_CLUSTER_SIMILARITY_SPLIT = 0.60
MIN_INTER_CLUSTER_SIMILARITY_MERGE = 0.80
